### ISSUE TITLE
slide failed to load SyntaxError: The requested module '/node_modules/react/jsx-runtime.js?v=9d5c9697' does not provide an export named 'Fragment'

### ISSUE THREAD

**Issue by Oluwasetemi** [AlbertBrand/slidev-addon-tldraw#3] opened 2024-09-30 18:14 UTC
Hi Albert,

I tried to use the addon and I got the above error? What do you think could be the issue? 

Here is my package.json

<details>
  <summary>Package.JSON</summary>
  <code>
  
  "dependencies": {
    "@slidev/cli": "^0.49.29",
    "@slidev/theme-default": "latest",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "slidev-addon-tldraw": "^0.2.3",
    "vue": "^3.5.10"
  },
  "devDependencies": {
    "@iconify-json/logos": "^1.2.0",
    "@iconify-json/mdi": "^1.2.0",
    "@slidev/types": "^0.49.29",
    "@vue/compiler-sfc": "^3.5.10",
    "markdown-it-magic-link": "^0.1.4",
    "nodemon": "^3.1.7",
    "playwright-chromium": "^1.47.2",
    "prettier": "^3.3.3",
    "prettier-plugin-slidev": "^1.0.5"
  },
  
  </code>
</details>

Here is the addons field on my formatter

![image](https://github.com/user-attachments/assets/be3dd911-77a0-47d4-9ed5-cb405acd5721)

**Comment by AlbertBrand** [comment] 2024-10-02 08:53
I can't reproduce with version 0.3.0, if I take an example presentation and use your package dependencies that presentation does not give an error. @Oluwasetemi Can you check if it still fails with v0.3.0? If not, I need a larger reproduction case.

**Comment by Oluwasetemi** [comment] 2024-10-02 08:55
@AlbertBrand will it right away and left you know if it works

**Comment by AlbertBrand** [comment] 2024-10-09 08:46
@Oluwasetemi did you try? Else I'll close this one.

**Comment by AlbertBrand** [comment] 2024-10-11 08:16
As discussed on Discord, in your configuration you have:
```
  optimizeDeps: {
    exclude: [
      '@vue/compiler-sfc', 'react', 'react-dom/client', '@babel/standalone'
    ],
  }
```
which caused React not to be part of the Vite bundling. As `tldraw` requires `react` and `react-dom` the page breaks when running it on the Vite dev server.

Make sure not to exclude React!

**Comment by AlbertBrand** [comment] 2024-10-11 08:16
Closing.

**Closed by AlbertBrand** 2024-10-11 08:16 UTC
